### PR TITLE
Advanced Building Blocks - Enumerables

### PR DESCRIPTION
**Pull request by ozovalihasan**
- All methods wanted on the project page are added.
- Ruby code is fixed by using Rubocop 
- I worked alone for this project

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work @ozovalihasan! :medal_military: 
Please lookout for some feedback in a few minutes

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by nikasulo** [comment]
Please consider the screenshot below. The following methods currently return some errors from testing: `my_each`, `my_each_with_index`, `my_any`, `my_none`, `my_map`

screenshot

Kindly look into the above errors, resolve them and request another review. I wish you the very best and see you at the top!

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by ozovalihasan** [comment]
- Problems related to my_each, my_each_with_index, my_any?, my_none? and my_map methods are fixed
- Errors found by Rubocop are fixed

**Review by stratospherique — APPROVED** [review]
### Great work implementing the suggested changes :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

###### PS: before you merge, kindly delete all commented/debugging code :pray:

**Comment by ozovalihasan** [comment]
Thanks for your feedback @stratospherique and @Oluwadamilareolusakin

**Pull request merged**
